### ISSUE TITLE
About the scripts.

### ISSUE THREAD

**Issue by Colezwhy** [CollaborativeVideoDiffusion/CVD#1]
Hi, thank you for your great job, which is very inspiring to me.
I wonder if the inference scripts are ready now? I would like to have a try on your models.

**Comment by zfkuang** [comment]
Hi,

Apologies for the delay, we'll upload the the inferences tutorial within a week.

**Comment by Colezwhy** [comment]
> Hi,
> 
> Apologies for the delay, we'll upload the the inferences tutorial within a week.

Thank you very much for your reply!

**Comment by Colezwhy** [comment]
Hi, would you please remind me if the scripts are updated? Thank you very much!

**Comment by zfkuang** [comment]
Thanks for your patient. We have updated the base with inference instructions. Let us know if you have any further questions.
